version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "master"
    open-pull-requests-limit: 10
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "monthly"
