name: Quality
on: [push]

jobs:
  check_prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install npm packages
        run: npm install
      - name: Check Prettier
        run: npx prettier --check .

  check_php_lint:
    runs-on: ubuntu-latest
    needs: ["check_prettier"]
    strategy:
      matrix:
        PHP_VERSION: ["8.2"]
    steps:
      - uses: actions/checkout@v5
      - name: "Setup PHP ${{ matrix.PHP_VERSION }}"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.PHP_VERSION }}"
          coverage: "none"
      - name: "Run phplint"
        run: |
          curl -Ls https://github.com/overtrue/phplint/releases/download/9.0.3/phplint.phar -o /usr/local/bin/phplint
          chmod +x /usr/local/bin/phplint
          /usr/local/bin/phplint -vvv --no-cache

  check_docker_build:
    runs-on: ubuntu-latest
    needs: ["check_php_lint"]
    steps:
      - uses: actions/checkout@v5
      - name: Build Docker Image
        run: docker build -t mock-saml2-idp:dev .
